export const ADD_CUSTOMER = "ADD_CUSTOMER";
export const REMOVE_CUSTOMER = "REMOVE_CUSTOMER";
export const FILTER_CUSTOMERS = "FILTER_CUSTOMERS";
export const CLEAR_FILTER = "CLEAR_FILTER";
export const UPDATE_CUSTOMER = "UPDATE_CUSTOMER";

export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";
export const USER_LOADED = "USER_LOADED";
export const AUTH_ERROR = "AUTH_ERROR";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGOUT = "LOGOUT";
export const CLEAR_ERRORS = "CLEAR_ERRORS";
export const REMOVE_ALERT = "REMOVE_ALERT";
export const SET_ALERT = "SET_ALERT";

export const GET_ACCOUNT = "GET_ACCOUNT";
export const ACCOUNTOWNERS_ERROR = "ACCOUNTOWNERS_ERROR";

export const GET_BENEFICIARIES = "GET_BENEFICIARIES";
export const BENEFICIARIES_ERROR = "BENEFICIARIES_ERROR";

export const ADD_BENEFICIARY = "ADD_BENEFICIARY";
export const BENEFICIARY_ERROR = "BENEFICIARY_ERROR";

export const UPDATE_BENEFICIARIES = "UPDATE_BENEFICIARIES";
export const UPDATE_BENEFICIARIES_ERROR = "UPDATE_BENEFICIARIES_ERROR";

export const CHANGE_PASSWORD = "CHANGE_PASSWORD";
export const CHANGE_PASSWORD_ERROR = "CHANGE_PASSWORD_ERROR";

export const GET_BENEFICIARY = "GET_BENEFICIARY";
// export const BENEFICIARY_ERROR = 'BENEFICIARY_ERROR'
export const USER_ERROR = "USER_ERROR";

export const GET_TRANSACTIONS = "GET_TRANSACTIONS";
export const PERSONNEL_LOGIN_SUCCESS = "PERSONNEL_LOGIN_SUCCESS";

export const GET_DEBTLIST = "GET_DEBTLIST";

export const ADD_DEBT = "ADD_DEBT";

export const POST_TRANSFERINTRABANK = "POST_TRANSFERINTRABANK";

export const POST_TRANSFERINTERBANK = "POST_TRANSFERINTERBANK";

export const GET_OTP = "GET_OTP";

export const VERIFY_OTP = "VERIFY_OTP";

export const DEL_DEBT = "DEL_DEBT";

export const GET_LIST_EMPLOYEES = "GET_LIST_EMPLOYEES";

export const ERROR = "ERROR";
export const DELETE_PERSONNEL = "DELETE_PERSONNEL";
export const UPDATE_PERSONNEL = "UPDATE_PERSONNEL";
export const LOADING = "LOADING";
export const ADD_PERSONNEL = "ADD_PERSONNEL";

export const UPDATE_DEBT = "UPDATE_DEBT";

export const SET_LOADING = "SET_LOADING";

export const ADD_MONEY = "ADD_MONEY";

export const ADDMONEY_ERROR = "ADDMONEY_ERROR";

export const CREATECUSTOMERACCOUNT_ERROR = "CREATECUSTOMERACCOUNT_ERROR";

export const CREATE_CUSTOMERACCOUNT = "CREATE_CUSTOMERACCOUNT";

export const GET_DEPOSITHISTORY = "GET_DEPOSITHISTORY";

export const GETDEPOSITHISTORY_ERROR = "GETDEPOSITHISTORY_ERROR";

export const GET_TRANSFERHISTORY = "GET_TRANSFERHISTORY";

export const GETTRANSFERTHISTORY_ERROR = "GETTRANSFERTHISTORY_ERROR";

export const GET_DEBTHISTORY = "GET_DEBTHISTORY";

export const GETDEBTHISTORY_ERROR = "GETDEBTHISTORY_ERROR";

export const REFRESH = "REFRESH";

export const GET_NOTIFS = "GET_NOTIFS";

export const ADD_NOTIFS = "ADD_NOTIFS";